---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmo-9b8b6ddc
  labels:
    app: mmo-9b8b6ddc
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mmo-9b8b6ddc
  template:
    metadata:
      labels:
        app: mmo-9b8b6ddc
    spec:
      containers:
        - name: mmo-9b8b6ddc
          image: docker.io/phengbunath/mmo-9b8b6ddc:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
